apiVersion: v1
kind: ConfigMap
metadata:
  name: http-client
data:
  # logging
  LOG_ENCODING: json

  # tracing
  ## jaeger general
  JAEGER_SERVICE_NAME: http-client
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  JAEGER_AGENT_PORT: "6831"
  ## grafana-tempo
  # JAEGER_AGENT_HOST: tempo.tracing.svc.cluster.local
  ## jaeger
  ### agent
  JAEGER_AGENT_HOST: jaeger-agent.tracing.svc.cluster.local
  ### bypass agent, directly to collector
  # JAEGER_ENDPOINT: http://jaeger-collector.tracing.svc.cluster.local:14268/api/traces

  # server
  REST_SERVER_HOST: http-server.apps.svc.cluster.local
  REST_SERVER_PORT: "8080"
